api/urls.py
from django.urls import path

from .views import (
    ProgramUpdateView, 
    ChairUpdateView, 
    MoiveDeleteView, 
    MoiveGetView,
    MoiveListView,
    MoivePostView, 
    MoiveUpdateView,
    CinemaRoomDeleteView, 
    CinemaRoomGetView,
    CinemaRoomListView,
    CinemaRoomPostView, 
    CinemaRoomUpdateView,
)


app_name = 'api'

urlpatterns = [
    path('v1/program/update/<int:pk>', ProgramUpdateView.as_view(), name='program_update'),

    path('v1/chair/update/<int:pk>', ChairUpdateView.as_view(), name='chair_update'),

    path('v1/movie/get/', MoiveListView.as_view(), name='list_movie'),
    path('v1/movie/get/<int:pk>', MoiveGetView.as_view(), name='get_movie'),
    path('v1/movie/delete/<int:pk>', MoiveDeleteView.as_view(), name='delete_movie'),
    path('v1/movie/update/<int:pk>', MoiveUpdateView.as_view(), name='update_movie'),
    path('v1/movie/post/', MoivePostView.as_view(), name='post_movie'),

    path('v1/cinemaroom/get/', CinemaRoomListView.as_view(), name='list_cinemaroom'),
    path('v1/cinemaroom/get/<int:pk>', CinemaRoomGetView.as_view(), name='get_cinemaroom'),
    path('v1/cinemaroom/delete/<int:pk>', CinemaRoomDeleteView.as_view(), name='delete_cinemaroom'),
    path('v1/cinemaroom/update/<int:pk>', CinemaRoomUpdateView.as_view(), name='update_cinemaroom'),
    path('v1/cinemaroom/post/', CinemaRoomPostView.as_view(), name='post_cinemaroom'),
]

cinema/urls.py
from django.urls import path, include, re_path

from .views import (
    CinemaRoomView, 
    ProgramView, 
    ChairView, 
    UpdateChiarView, 
    register_request,
    login_request,
    logout_request
)

app_name = 'cinema'

urlpatterns = [
    path('', CinemaRoomView.as_view(), name='home'),
    path('program/<int:cinema_room_id>', ProgramView.as_view(), name='program'),
    path('program/chair/<int:program_id>', ChairView.as_view(), name='chair'),
    path('program/chair/update/<int:pk>', UpdateChiarView.as_view(), name='update_chair'),
    path("register", register_request, name="register"),
    path("login", login_request, name="login"),
    path("logout", logout_request, name= "logout"),


]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cinema.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cinema/models.py
from django.db import models
from django.contrib.auth.models import User


class Movie(models.Model):
    name = models.CharField(max_length=50)
    director = models.CharField(max_length=50)
    duration = models.DurationField()
    poster = models.ImageField(upload_to='media/', height_field=None, width_field=None, max_length=None)

    def __str__(self):
        return self.name


class CinemaRoom(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Program(models.Model):
    cinema_room = models.ForeignKey(CinemaRoom, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    show = models.DateTimeField(auto_now=False, auto_now_add=False)

    def __str__(self):
        return f'{self.cinema_room} {self.movie} {self.status} {self.show}'


class Chair(models.Model):
    program = models.ForeignKey(Program, on_delete=models.CASCADE, default=None)
    number = models.IntegerField()
    salesـstatus = models.BooleanField(default=False)

    def __str__(self):
        return f' {self.program} {self.number}'

cinema/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

cinema/views.py
from django.views.generic import ListView, UpdateView
from django.shortcuts import  render, redirect
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout 
from django.contrib.auth.mixins import LoginRequiredMixin


from .models import CinemaRoom, Program, Chair
from .forms import NewUserForm


class CinemaRoomView(ListView):
    context_object_name = 'cinema_object'

    def get_queryset(self):
        return CinemaRoom.objects.all()


class ProgramView(ListView):
    context_object_name = 'program_object'

    def get_queryset(self):
        cinema_room_id = self.kwargs.get('cinema_room_id')
        return Program.objects.filter(cinema_room_id=cinema_room_id)


class ChairView(ListView):
    context_object_name = 'chair_object'

    def get_queryset(self):
        program_id = self.kwargs.get('program_id')
        return Chair.objects.filter(program_id=program_id)


class UpdateChiarView(LoginRequiredMixin, UpdateView):
	model = Chair
	fields = ['salesـstatus'] 
	template_name = 'cinema/update_status_chair.html' 
	success_url="/"

	login_url = '/login'
	redirect_field_name = '/login'


def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("cinema:home")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request=request, template_name="registration/register.html", context={"register_form":form})


def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("cinema:home")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="registration/login.html", context={"login_form":form})


def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.") 
	return render(request=request, template_name="registration/logout.html")

templates/cinema/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title> {% block title %}{% endblock %} </title>

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    </head>

    <body>
        <ul class="nav nav-tabs d-flex justify-content-start align-items-start">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'cinema:home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'cinema:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'cinema:register' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'cinema:logout' %}">Logout</a>
              </li>
          </ul>
        <div style="height: 100vh; gap:8px" class="d-flex justify-content-center align-items-center flex-wrap">
            {% block main %}

            {% endblock %}
        </div>
    </body>

</html>

templates/cinema/chair_list.html
{% extends 'cinema/base.html' %}


{% block title %} seats {% endblock %}


{% block main %}

    {% for object in chair_object %}

        <div class="card">
            <div class="card-header">
                {{ object.program.cinema_room }} - {{ object.program.movie }}
            </div>
            <div class="card-body">
                <h5 class="card-title"> seat number: {{ object.number }}</h5>
                <p class="card-text">availability: {{ object.salesـstatus }}</p>
                <form action="{% url 'cinema:update_chair' object.pk %}" >
                    {% if object.salesـstatus %}
                        <input class="btn btn-primary" type="submit" name="submit" value="Reservation" disabled/>
                    {% else %}
                        <input class="btn btn-primary" type="submit" name="submit" value="Reservation" />
                    {% endif %}
                </form>
            </div>
        </div>

    {% empty %}
        <div> Nothing to show </div>
    {% endfor %}

{% endblock %}

templates/cinema/cinemaroom_list.html
{% extends 'cinema/base.html' %}

{% block title %} rooms {% endblock %}


{% block main %}

    {% for object in cinema_object %}

        <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">{{ object.name }}</h5>
              <p class="card-text">This is the biggest room of this cinema</p>
              <a href="{% url 'cinema:program' object.pk %}" class="btn btn-primary">See programs</a>
            </div>
        </div>

    {% empty %}
        <div> Nothing to show </div>
    {% endfor %}

{% endblock %}

templates/cinema/program_list.html
{% extends 'cinema/base.html' %}

{% block title %} programs {% endblock %}

{% block main %}

    {% for object in program_object %}

        <div class="card" style="width: 18rem;">
            <img src="http://127.0.0.1:8000/{{ object.movie.poster }}" class="card-img-top" alt="{{ object.movie.poster }}" width="100" height="200">
            <div class="card-body">
              <h5 class="card-title">room : {{ object.cinema_room }}</h5>
              <p class="card-text">movie name: {{ object.movie }}</p>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">status: {{ object.status }}</li>
              <li class="list-group-item">director: {{ object.movie.director }}</li>
              <li class="list-group-item">duration: {{ object.movie.duration }}</li>
              <li class="list-group-item">show: {{ object.show }}</li>
            </ul>
            <div class="card-body">
              <a href="{% url 'cinema:home' %}" class="card-link">Back</a>
              <a href="{% url 'cinema:chair' object.pk %}" class="card-link">See Chairs</a>
            </div>
          </div>

    {% empty %}
        <div> Nothing to show </div>
    {% endfor %}

{% endblock %}

templates/cinema/update_status_chair.html
{% extends 'cinema/base.html' %}


{% block title %} buy  {% endblock %}


{% block main %}

    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">Reservation</h5>
            <p class="card-text">Enjoy your shopping</p>
            <form method="POST">{% csrf_token %}
        
                {{ form.as_p }} 
        
                <input type="submit" name="submit" value="Buy" class="btn btn-success">
            </form>
        </div>
      </div>

{% endblock %}